"""empty message

Revision ID: 31fd3ab6ab53
Revises: b58400c6b15a
Create Date: 2022-04-08 10:23:02.295993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fd3ab6ab53'
down_revision = 'b58400c6b15a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icecream_join_shop')
    op.add_column('icecreams', sa.Column('shop_id', sa.Integer(), nullable=False))
    op.drop_constraint('icecreams_user_id_fkey', 'icecreams', type_='foreignkey')
    op.create_foreign_key(None, 'icecreams', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'icecreams', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'icecreams', type_='foreignkey')
    op.drop_constraint(None, 'icecreams', type_='foreignkey')
    op.create_foreign_key('icecreams_user_id_fkey', 'icecreams', 'users', ['user_id'], ['id'])
    op.drop_column('icecreams', 'shop_id')
    op.create_table('icecream_join_shop',
    sa.Column('ice_cream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ice_cream_id'], ['icecreams.id'], name='icecream_join_shop_ice_cream_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name='icecream_join_shop_shop_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ice_cream_id', 'shop_id', name='icecream_join_shop_pkey')
    )
    # ### end Alembic commands ###
