"""empty message

Revision ID: 60237918dc46
Revises: 007386c33799
Create Date: 2022-04-04 21:15:30.827045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60237918dc46'
down_revision = '007386c33799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_like',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('review_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_like')
    # ### end Alembic commands ###
