"""onDelete added to icecream_join_shop

Revision ID: 034128eb9289
Revises: 60237918dc46
Create Date: 2022-04-07 16:55:28.604375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034128eb9289'
down_revision = '60237918dc46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('icecream_join_shop_shop_id_fkey', 'icecream_join_shop', type_='foreignkey')
    op.drop_constraint('icecream_join_shop_ice_cream_id_fkey', 'icecream_join_shop', type_='foreignkey')
    op.create_foreign_key(None, 'icecream_join_shop', 'icecreams', ['ice_cream_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'icecream_join_shop', 'shops', ['shop_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'icecream_join_shop', type_='foreignkey')
    op.drop_constraint(None, 'icecream_join_shop', type_='foreignkey')
    op.create_foreign_key('icecream_join_shop_ice_cream_id_fkey', 'icecream_join_shop', 'icecreams', ['ice_cream_id'], ['id'])
    op.create_foreign_key('icecream_join_shop_shop_id_fkey', 'icecream_join_shop', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###
