"""empty message

Revision ID: 271cf9d35924
Revises: 02b87161a64d
Create Date: 2022-04-04 17:46:18.220355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271cf9d35924'
down_revision = '02b87161a64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ice_cream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ice_cream_id'], ['icecreams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
