"""empty message

Revision ID: b58400c6b15a
Revises: 7c2da3a35f34
Create Date: 2022-04-07 21:25:47.339756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58400c6b15a'
down_revision = '7c2da3a35f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('shop_pic_url', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'shop_pic_url')
    # ### end Alembic commands ###
