"""empty message

Revision ID: 007386c33799
Revises: 271cf9d35924
Create Date: 2022-04-04 14:17:47.493192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007386c33799'
down_revision = '271cf9d35924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street_name', sa.String(length=150), nullable=False),
    sa.Column('street_number', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icecream_join_shop',
    sa.Column('ice_cream_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ice_cream_id'], ['icecreams.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('ice_cream_id', 'shop_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icecream_join_shop')
    op.drop_table('shops')
    # ### end Alembic commands ###
